// Siemens Energy Atlassian DC → Cloud Migration Assessment
// 10 themes × 4 sub-dimensions × 5 questions = 200 questions

export const THEMES = [
  { name: "Cloud Migration Strategy & Governance", description: "Vision, business case, governance and financial management for the Atlassian cloud migration programme", weight: 0.12 },
  { name: "Atlassian Instance Architecture", description: "Consolidation strategy across 4 Jira, 3 JSM and 1 Confluence DC instances", weight: 0.12 },
  { name: "Application Portfolio Readiness", description: "Cloud availability, complexity and rationalisation of 65 marketplace apps", weight: 0.14 },
  { name: "Security, Identity & Compliance", description: "Identity federation, SSO, data residency, access controls and audit capabilities", weight: 0.12 },
  { name: "Data Migration & Quality", description: "Classification, tooling, validation and retention of data across all instances", weight: 0.10 },
  { name: "Integration & API Landscape", description: "External system integrations including SAP, Salesforce, Azure DevOps and custom APIs", weight: 0.10 },
  { name: "Cloud Operating Model", description: "Team structure, support model, change management and training for cloud operations", weight: 0.10 },
  { name: "Testing & Quality Assurance", description: "Test management strategy, UAT, performance testing and regression frameworks", weight: 0.08 },
  { name: "Automation & DevOps Maturity", description: "Automation adoption, CI/CD, monitoring and workflow automation complexity", weight: 0.08 },
  { name: "Agentic AI & Innovation Readiness", description: "AI strategy, Atlassian Intelligence, Rovo adoption and agentic workflow opportunities", weight: 0.04 },
];

export const SUB_DIMENSIONS = {
  "Cloud Migration Strategy & Governance": [
    { name: "Migration Vision & Business Case", description: "Strategic rationale and financial justification for Atlassian cloud migration" },
    { name: "Cloud Governance Framework", description: "Policies, standards and decision-making structures for cloud operations" },
    { name: "FinOps & Cost Management", description: "Cloud cost visibility, allocation, forecasting and optimisation" },
    { name: "Risk Management & Compliance", description: "Migration risk identification, assessment and mitigation strategies" },
  ],
  "Atlassian Instance Architecture": [
    { name: "Instance Consolidation Strategy", description: "Plan to consolidate 4 Jira + 3 JSM + 1 Confluence DC instances to cloud" },
    { name: "Multi-Instance User Management", description: "User lifecycle management across all Atlassian DC instances" },
    { name: "Project & Space Architecture", description: "Project taxonomy, space structure and governance across instances" },
    { name: "Data Volume & Performance", description: "Data sizing, performance baselines and cloud capacity planning" },
  ],
  "Application Portfolio Readiness": [
    { name: "Marketplace App Cloud Availability", description: "Assessment of cloud equivalents for all 65 DC marketplace apps" },
    { name: "Custom Code & ScriptRunner Complexity", description: "Inventory and complexity assessment of ScriptRunner scripts and custom code" },
    { name: "Integration & API Dependencies", description: "App-to-app and app-to-external-system integration dependencies" },
    { name: "App Rationalisation & Decommissioning", description: "Strategy to retire, consolidate or replace apps not needed in cloud" },
  ],
  "Security, Identity & Compliance": [
    { name: "Identity Federation & SSO (Atlassian Access)", description: "Transition from SAML SSO apps to Atlassian Access/Guard for unified identity" },
    { name: "Data Residency & Sovereignty", description: "Data location requirements, residency options and compliance obligations" },
    { name: "Access Controls & Admin Governance", description: "Role-based access, admin privileges and governance across cloud instances" },
    { name: "Audit, Monitoring & Incident Response", description: "Audit logging, security monitoring and incident response capabilities" },
  ],
  "Data Migration & Quality": [
    { name: "Data Classification & Sensitivity", description: "Classification of data across Jira, JSM and Confluence for migration risk" },
    { name: "Migration Tooling & Automation", description: "Tools and automation for data migration including Atlassian Migration Assistant" },
    { name: "Data Validation & Integrity", description: "Validation processes to ensure data integrity post-migration" },
    { name: "Historical Data Retention Strategy", description: "Approach to archiving and retaining historical data from DC instances" },
  ],
  "Integration & API Landscape": [
    { name: "External System Integrations", description: "Catalogue of external system integrations dependent on Atlassian DC" },
    { name: "Salesforce & SAP Connectivity", description: "Salesforce and SAP integration patterns and cloud migration impact" },
    { name: "DevOps Toolchain Integration", description: "Azure DevOps, Git and CI/CD pipeline integrations with Atlassian tools" },
    { name: "API Management & Versioning", description: "REST API dependency management and version compatibility for cloud APIs" },
  ],
  "Cloud Operating Model": [
    { name: "Team Structure & Cloud CoE", description: "Cloud Centre of Excellence establishment and team capability for Atlassian cloud" },
    { name: "Support Model & SLA Transformation", description: "Transition from DC-based support to cloud-native support model" },
    { name: "Change Management & Adoption", description: "User adoption strategy for cloud Atlassian tools across 24K+ users" },
    { name: "Training & Skills Development", description: "Training programme for administrators and end users on Atlassian Cloud" },
  ],
  "Testing & Quality Assurance": [
    { name: "Test Management Tool Strategy (Xray vs Zephyr)", description: "Rationalisation of Xray and Zephyr Essential test management tools" },
    { name: "UAT & Migration Validation", description: "User acceptance testing approach for validating cloud migration" },
    { name: "Performance & Load Testing", description: "Performance testing to validate cloud instance performance at scale" },
    { name: "Regression Testing Framework", description: "Automated regression testing to validate post-migration functionality" },
  ],
  "Automation & DevOps Maturity": [
    { name: "Automation for Jira Cloud Adoption", description: "Readiness to adopt native Automation for Jira Cloud replacing complex DC apps" },
    { name: "CI/CD & Infrastructure as Code", description: "CI/CD pipeline maturity and IaC adoption for Atlassian configuration management" },
    { name: "Monitoring, Alerting & Observability", description: "Observability capabilities for Atlassian Cloud platform health monitoring" },
    { name: "Workflow Automation Complexity", description: "Complexity assessment of ScriptRunner, JMWE and Jira Workflow Toolbox automations" },
  ],
  "Agentic AI & Innovation Readiness": [
    { name: "AI Strategy & Data Foundation", description: "Organisation's readiness to adopt AI capabilities within Atlassian Cloud" },
    { name: "Atlassian Intelligence & Rovo Adoption", description: "Readiness to activate Atlassian Intelligence and Rovo agents post-migration" },
    { name: "Agentic Workflow Opportunities", description: "Identification of workflows that can be automated via Rovo Agents" },
    { name: "AI Governance & Ethics", description: "Policies and controls governing AI use within the Atlassian estate" },
  ],
};

export const QUESTION_TEMPLATES = [
  "To what extent is {sub_dim} defined, documented and approved, with clear ownership and review cadence across all Siemens Energy Atlassian instances?",
  "How consistently is {sub_dim} implemented across all 4 Jira Software instances, 3 JSM instances and the Confluence instance, including governance over exceptions?",
  "What tooling and automation support {sub_dim} end-to-end, and how integrated are these with Siemens Energy's broader IT landscape (SAP, Salesforce, Azure DevOps)?",
  "Which metrics/KPIs evidence the effectiveness of {sub_dim} today, and are these benchmarked against Atlassian Cloud targets?",
  "How mature is continuous improvement for {sub_dim} within Siemens Energy, with specific reference to lessons learned from prior Atlassian upgrades or migrations?",
];

// All 65 marketplace apps
export const APPLICATIONS = [
  // Confluence apps
  {
    name: "Comala Lists DC - Confluence",
    product: "confluence",
    vendor: "Comala Tech",
    user_tier: 80000,
    annual_cost_usd: 12000,
    cloud_available: "partial",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Cloud version available with reduced feature set",
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 1,
  },
  // Jira Software apps
  {
    name: "Extender for Jira DC",
    product: "jira_software",
    vendor: "Riada",
    user_tier: 500,
    annual_cost_usd: 1790,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 2,
  },
  {
    name: "Issue Type Filters DC",
    product: "jira_software",
    vendor: "OBSS",
    user_tier: 2000,
    annual_cost_usd: 1999,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 3,
  },
  {
    name: "Tableau Connector Pro DC",
    product: "jira_software",
    vendor: "K15t",
    user_tier: 20000,
    annual_cost_usd: 25500,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Validate Tableau Cloud vs DC connector feature parity",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 4,
  },
  {
    name: "Refined for JSM DC",
    product: "jira_service_management",
    vendor: "Refined",
    user_tier: 2000,
    annual_cost_usd: 13515,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Portal customisation needs re-implementation in cloud",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 5,
  },
  {
    name: "ScriptRunner for Jira DC",
    product: "jira_software",
    vendor: "Adaptavist",
    user_tier: 500,
    annual_cost_usd: 5105,
    cloud_available: "yes",
    migration_complexity: "high",
    migration_path: "migrate",
    migration_notes: "Scripts must be reviewed and rewritten for Cloud API restrictions; Groovy to cloud Groovy migration required",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: "Agentic automation to replace manual ScriptRunner scripts with Rovo Agents",
    ord: 6,
  },
  {
    name: "Queues for Jira & JSM DC",
    product: "jira_service_management",
    vendor: "Deviniti",
    user_tier: 2000,
    annual_cost_usd: 4934,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 7,
  },
  {
    name: "Timesheets by Tempo DC",
    product: "jira_software",
    vendor: "Tempo",
    user_tier: 20000,
    annual_cost_usd: 77056,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Tempo Cloud has full feature parity; data migration via Tempo migration tools",
    phase: 3,
    is_critical: 1,
    agentic_opportunity: "AI-powered timesheet completion suggestions and anomaly detection",
    ord: 8,
  },
  {
    name: "User/Group Export & License Optimizer DC",
    product: "jira_software",
    vendor: "Decadis",
    user_tier: 2000,
    annual_cost_usd: 2499,
    cloud_available: "partial",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: "Partial cloud functionality; Atlassian Access covers most user management needs",
    phase: 1,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 9,
  },
  {
    name: "Jira Workflow Toolbox DC",
    product: "jira_software",
    vendor: "Toolbox for Jira",
    user_tier: 2000,
    annual_cost_usd: 6600,
    cloud_available: "yes",
    migration_complexity: "high",
    migration_path: "migrate",
    migration_notes: "Workflow conditions and validators need thorough review for cloud compatibility",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 10,
  },
  {
    name: "JSU Automation Suite DC",
    product: "jira_software",
    vendor: "Codebarrel",
    user_tier: 20000,
    annual_cost_usd: 19000,
    cloud_available: "partial",
    migration_complexity: "high",
    migration_path: "replace",
    migration_notes: "Replace with native Automation for Jira Cloud; audit all JSU rules and re-implement",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 11,
  },
  {
    name: "Multiple Filters Chart Gadgets DC",
    product: "jira_software",
    vendor: "Deviniti",
    user_tier: 2000,
    annual_cost_usd: 2475,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 12,
  },
  {
    name: "SAML SSO for Jira DC (20k)",
    product: "jira_software",
    vendor: "resolution",
    user_tier: 20000,
    annual_cost_usd: 30630,
    cloud_available: "not_required",
    migration_complexity: "low",
    migration_path: "not_required",
    migration_notes: "Retire - Atlassian Access provides SSO via SAML/OIDC natively in Cloud",
    phase: 1,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 13,
  },
  {
    name: "My User Manager for Jira DC",
    product: "jira_software",
    vendor: "Appfire",
    user_tier: 20000,
    annual_cost_usd: 10500,
    cloud_available: "not_required",
    migration_complexity: "low",
    migration_path: "not_required",
    migration_notes: "Retire - Atlassian Access/Guard provides user management in Cloud",
    phase: 1,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 14,
  },
  {
    name: "SAML SSO for Jira DC (500)",
    product: "jira_software",
    vendor: "resolution",
    user_tier: 500,
    annual_cost_usd: 5674,
    cloud_available: "not_required",
    migration_complexity: "low",
    migration_path: "not_required",
    migration_notes: "Retire - Atlassian Access provides SSO via SAML/OIDC natively in Cloud",
    phase: 1,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 15,
  },
  {
    name: "Xray Test Management DC",
    product: "jira_software",
    vendor: "Xpand IT",
    user_tier: 500,
    annual_cost_usd: 13013,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Xray Cloud is actively developed; consolidation opportunity - retire Zephyr Essential",
    phase: 3,
    is_critical: 1,
    agentic_opportunity: "Rovo Agent for automated test case generation from Jira stories",
    ord: 16,
  },
  {
    name: "Zephyr Essential DC",
    product: "jira_software",
    vendor: "SmartBear",
    user_tier: 20000,
    annual_cost_usd: 78126,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "replace",
    migration_notes: "CONSOLIDATION OPPORTUNITY: Customer runs both Xray and Zephyr simultaneously. Recommend consolidating to Xray Cloud - saving ~$78K/yr",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 17,
  },
  {
    name: "Power BI Connector DC (2k)",
    product: "jira_software",
    vendor: "Algoloop",
    user_tier: 2000,
    annual_cost_usd: 15211,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Validate OAuth connectivity to Power BI in cloud environment",
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 18,
  },
  {
    name: "Exporter for Jira DC",
    product: "jira_software",
    vendor: "Botron Software",
    user_tier: 2000,
    annual_cost_usd: 3120,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 19,
  },
  {
    name: "SAML SSO for Jira DC (500b)",
    product: "jira_software",
    vendor: "resolution",
    user_tier: 500,
    annual_cost_usd: 7020,
    cloud_available: "not_required",
    migration_complexity: "low",
    migration_path: "not_required",
    migration_notes: "Retire - Atlassian Access provides SSO via SAML/OIDC natively in Cloud",
    phase: 1,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 20,
  },
  {
    name: "Secure Fields DC",
    product: "jira_software",
    vendor: "Novalight",
    user_tier: 20000,
    annual_cost_usd: 9200,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Validate data encryption approach in cloud",
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 21,
  },
  {
    name: "Smart Checklists for Jira DC",
    product: "jira_software",
    vendor: "eDOT Solutions",
    user_tier: 20000,
    annual_cost_usd: 8600,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 22,
  },
  {
    name: "Epic Clone DC",
    product: "jira_software",
    vendor: "Botron Software",
    user_tier: 20000,
    annual_cost_usd: 10600,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 23,
  },
  {
    name: "Configuration Manager for Jira (CMJ) DC (20k)",
    product: "jira_software",
    vendor: "Botron Software",
    user_tier: 20000,
    annual_cost_usd: 38500,
    cloud_available: "partial",
    migration_complexity: "very_high",
    migration_path: "replace",
    migration_notes: "Replace with Jira Cloud Migration Assistant + native configuration management; CMJ has no direct cloud equivalent",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 24,
  },
  {
    name: "ScriptRunner for Jira DC (2k)",
    product: "jira_software",
    vendor: "Adaptavist",
    user_tier: 2000,
    annual_cost_usd: 12395,
    cloud_available: "yes",
    migration_complexity: "high",
    migration_path: "migrate",
    migration_notes: "Scripts must be reviewed and rewritten for Cloud API restrictions",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: "Agentic automation to replace manual ScriptRunner scripts with Rovo Agents",
    ord: 25,
  },
  {
    name: "Elements Connect DC (2k)",
    product: "jira_software",
    vendor: "Elements",
    user_tier: 2000,
    annual_cost_usd: 15300,
    cloud_available: "yes",
    migration_complexity: "high",
    migration_path: "migrate",
    migration_notes: "External data source connections need reconfiguring for cloud network access",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: "Agentic data synchronisation and validation agent",
    ord: 26,
  },
  {
    name: "BigPicture Portfolio DC",
    product: "jira_software",
    vendor: "SoftwarePlant",
    user_tier: 20000,
    annual_cost_usd: 56500,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "BigPicture Cloud actively developed; validate Advanced Roadmaps vs BigPicture feature parity",
    phase: 3,
    is_critical: 1,
    agentic_opportunity: "Rovo Agent for automated portfolio status reporting and risk identification",
    ord: 27,
  },
  {
    name: "BigPicture Enterprise DC",
    product: "jira_software",
    vendor: "SoftwarePlant",
    user_tier: 20000,
    annual_cost_usd: 34500,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Consolidation opportunity with BigPicture Portfolio - assess whether both tiers needed",
    phase: 4,
    is_critical: 0,
    agentic_opportunity: "Rovo Agent for automated portfolio status reporting and risk identification",
    ord: 28,
  },
  {
    name: "Connector for Salesforce & Jira DC",
    product: "jira_software",
    vendor: "Appfire",
    user_tier: 2000,
    annual_cost_usd: 14000,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Validate OAuth and Salesforce Connected App configuration for cloud",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 29,
  },
  {
    name: "Create on Transition DC",
    product: "jira_software",
    vendor: "Deviniti",
    user_tier: 2000,
    annual_cost_usd: 5900,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Assess whether native Automation for Jira Cloud can replace this app",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 30,
  },
  {
    name: "Three Dimensional Date Gadgets DC",
    product: "jira_software",
    vendor: "Deviniti",
    user_tier: 2000,
    annual_cost_usd: 200,
    cloud_available: "partial",
    migration_complexity: "low",
    migration_path: "retire",
    migration_notes: "Low value app; retire and use native Jira Cloud dashboard gadgets",
    phase: 1,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 31,
  },
  {
    name: "Power Admin for Jira DC",
    product: "jira_software",
    vendor: "Adaptavist",
    user_tier: 20000,
    annual_cost_usd: 9300,
    cloud_available: "partial",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Limited cloud equivalent; assess Atlassian Guard for admin functionality",
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 32,
  },
  {
    name: "Rich Filters for Jira Dashboards DC (20k)",
    product: "jira_software",
    vendor: "Deviniti",
    user_tier: 20000,
    annual_cost_usd: 17000,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 33,
  },
  {
    name: "Agile User Story Map DC",
    product: "jira_software",
    vendor: "Deviniti",
    user_tier: 20000,
    annual_cost_usd: 5000,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 34,
  },
  {
    name: "Checklists for Jira Enterprise DC",
    product: "jira_software",
    vendor: "Atlassian",
    user_tier: 500,
    annual_cost_usd: 1758,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 35,
  },
  {
    name: "SAML SSO for Jira DC (2k)",
    product: "jira_software",
    vendor: "resolution",
    user_tier: 2000,
    annual_cost_usd: 10320,
    cloud_available: "not_required",
    migration_complexity: "low",
    migration_path: "not_required",
    migration_notes: "Retire - Atlassian Access provides SSO via SAML/OIDC natively in Cloud",
    phase: 1,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 36,
  },
  {
    name: "Power BI Connector DC (20k)",
    product: "jira_software",
    vendor: "Algoloop",
    user_tier: 20000,
    annual_cost_usd: 28123,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Consolidation opportunity with Power BI Connector DC (2k) - assess if two licenses needed",
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 37,
  },
  {
    name: "CMJ DC (500)",
    product: "jira_software",
    vendor: "Botron Software",
    user_tier: 500,
    annual_cost_usd: 9550,
    cloud_available: "partial",
    migration_complexity: "very_high",
    migration_path: "replace",
    migration_notes: "Replace with Jira Cloud Migration Assistant + native configuration management",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 38,
  },
  {
    name: "Agile Hive SAFe DC",
    product: "jira_software",
    vendor: "Agile Hive",
    user_tier: 500,
    annual_cost_usd: 32588,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "SAFe programme management - validate cloud feature parity for PI planning",
    phase: 4,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 39,
  },
  {
    name: "ScriptRunner for Jira DC (500b)",
    product: "jira_software",
    vendor: "Adaptavist",
    user_tier: 500,
    annual_cost_usd: 4126,
    cloud_available: "yes",
    migration_complexity: "high",
    migration_path: "migrate",
    migration_notes: "Scripts must be reviewed and rewritten for Cloud API restrictions",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: "Agentic automation to replace manual ScriptRunner scripts with Rovo Agents",
    ord: 40,
  },
  {
    name: "JSU Automation Suite DC (2k)",
    product: "jira_software",
    vendor: "Codebarrel",
    user_tier: 2000,
    annual_cost_usd: 5000,
    cloud_available: "partial",
    migration_complexity: "high",
    migration_path: "replace",
    migration_notes: "Replace with native Automation for Jira Cloud",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 41,
  },
  {
    name: "ScriptRunner for Jira DC (20k)",
    product: "jira_software",
    vendor: "Adaptavist",
    user_tier: 20000,
    annual_cost_usd: 58500,
    cloud_available: "yes",
    migration_complexity: "high",
    migration_path: "migrate",
    migration_notes: "CRITICAL: Highest cost ScriptRunner license; scripts must be fully audited and rewritten for cloud",
    phase: 3,
    is_critical: 1,
    agentic_opportunity: "Agentic automation to replace manual ScriptRunner scripts with Rovo Agents",
    ord: 42,
  },
  {
    name: "Jira CLI DC",
    product: "jira_software",
    vendor: "Appfire",
    user_tier: 20000,
    annual_cost_usd: 27500,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "CLI scripts need updating for REST API v3 cloud endpoints",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 43,
  },
  {
    name: "Rich Filters DC (500)",
    product: "jira_software",
    vendor: "Deviniti",
    user_tier: 500,
    annual_cost_usd: 4900,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 44,
  },
  {
    name: "Integrity Check for Jira DC",
    product: "jira_software",
    vendor: "Botron Software",
    user_tier: 20000,
    annual_cost_usd: 9300,
    cloud_available: "partial",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Limited cloud equivalent; Atlassian Cloud handles most integrity checks natively",
    phase: 1,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 45,
  },
  {
    name: "My Requests Extension JSM DC",
    product: "jira_service_management",
    vendor: "Appfire",
    user_tier: 2000,
    annual_cost_usd: 4554,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 46,
  },
  {
    name: "Multi-Level Cascading Select DC",
    product: "jira_software",
    vendor: "Railsware",
    user_tier: 2000,
    annual_cost_usd: 1675,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 47,
  },
  {
    name: "Structure by Tempo DC",
    product: "jira_software",
    vendor: "Tempo",
    user_tier: 500,
    annual_cost_usd: 8517,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Structure Cloud available; validate hierarchy and formula fields in cloud",
    phase: 4,
    is_critical: 1,
    agentic_opportunity: "AI-driven resource allocation recommendations",
    ord: 48,
  },
  {
    name: "Jira Misc Workflow Extensions (JMWE) DC",
    product: "jira_software",
    vendor: "Innovalog",
    user_tier: 2000,
    annual_cost_usd: 6600,
    cloud_available: "yes",
    migration_complexity: "high",
    migration_path: "migrate",
    migration_notes: "Workflow post-functions and validators need review; assess migration to native Automation for Jira",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 49,
  },
  {
    name: "Enhanced API Authentication DC",
    product: "jira_software",
    vendor: "Appfire",
    user_tier: 20000,
    annual_cost_usd: 5975,
    cloud_available: "not_required",
    migration_complexity: "low",
    migration_path: "not_required",
    migration_notes: "Retire - Atlassian Access handles API authentication in cloud",
    phase: 1,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 50,
  },
  {
    name: "Git Integration for Jira DC",
    product: "jira_software",
    vendor: "BigBrassBand",
    user_tier: 20000,
    annual_cost_usd: 13398,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Git Integration Cloud available; validate Azure DevOps and GitHub connectivity",
    phase: 2,
    is_critical: 0,
    agentic_opportunity: "AI code review assistant integrated with Jira development workflow",
    ord: 51,
  },
  // More Confluence apps
  {
    name: "AURA Content Formatting Macros DC",
    product: "confluence",
    vendor: "Appfire",
    user_tier: 80000,
    annual_cost_usd: 45000,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: "AURA Cloud available with full macro support",
    phase: 2,
    is_critical: 1,
    agentic_opportunity: null,
    ord: 52,
  },
  {
    name: "Table Filter Charts Spreadsheets DC",
    product: "confluence",
    vendor: "StiltSoft",
    user_tier: 80000,
    annual_cost_usd: 56460,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: "Cloud version available; validate complex spreadsheet formulas",
    phase: 2,
    is_critical: 1,
    agentic_opportunity: null,
    ord: 53,
  },
  {
    name: "LaTeX Math DC",
    product: "confluence",
    vendor: "Bob Swift",
    user_tier: 80000,
    annual_cost_usd: 30200,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: "LaTeX Math Cloud available",
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 54,
  },
  {
    name: "draw.io Diagrams DC",
    product: "confluence",
    vendor: "JGraph",
    user_tier: 80000,
    annual_cost_usd: 46000,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: "draw.io Cloud fully supported; diagrams migrate with pages",
    phase: 2,
    is_critical: 1,
    agentic_opportunity: null,
    ord: 55,
  },
  // NEW apps
  {
    name: "Better Excel Exporter DC",
    product: "jira_software",
    vendor: "Midori",
    user_tier: 20000,
    annual_cost_usd: 13490,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 56,
  },
  {
    name: "Dynamic Forms for Jira DC",
    product: "jira_software",
    vendor: "Deviniti",
    user_tier: 20000,
    annual_cost_usd: 23719,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Validate dynamic form conditions work in cloud environment",
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 57,
  },
  {
    name: "Elements Connect DC (20k)",
    product: "jira_software",
    vendor: "Elements",
    user_tier: 20000,
    annual_cost_usd: 34800,
    cloud_available: "yes",
    migration_complexity: "high",
    migration_path: "migrate",
    migration_notes: "External data source connections need reconfiguring for cloud network access; SAP/Salesforce connectivity",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: "Agentic data synchronisation and validation agent",
    ord: 58,
  },
  {
    name: "Enhancer Plugin for Jira DC",
    product: "jira_software",
    vendor: "Decadis",
    user_tier: 20000,
    annual_cost_usd: 13000,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 59,
  },
  {
    name: "Jira Misc Custom Fields (JMCF) DC",
    product: "jira_software",
    vendor: "Innovalog",
    user_tier: 20000,
    annual_cost_usd: 14000,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Custom field behaviours need review for cloud compatibility",
    phase: 3,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 60,
  },
  {
    name: "JQL Tricks for Jira DC",
    product: "jira_software",
    vendor: "Deviniti",
    user_tier: 20000,
    annual_cost_usd: 6000,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 61,
  },
  {
    name: "Structure by Tempo DC (20k)",
    product: "jira_software",
    vendor: "Tempo",
    user_tier: 20000,
    annual_cost_usd: 64054,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "Largest Structure license; validate hierarchy and formula fields in cloud",
    phase: 4,
    is_critical: 1,
    agentic_opportunity: "AI-driven resource allocation recommendations",
    ord: 62,
  },
  {
    name: "sumUp for Jira DC",
    product: "jira_software",
    vendor: "Deviniti",
    user_tier: 20000,
    annual_cost_usd: 13200,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 63,
  },
  {
    name: "Table Grid Next Generation DC",
    product: "jira_software",
    vendor: "Deviniti",
    user_tier: 20000,
    annual_cost_usd: 8855,
    cloud_available: "yes",
    migration_complexity: "low",
    migration_path: "migrate",
    migration_notes: null,
    phase: 2,
    is_critical: 0,
    agentic_opportunity: null,
    ord: 64,
  },
  {
    name: "Time to SLA DC",
    product: "jira_service_management",
    vendor: "Deviniti",
    user_tier: 20000,
    annual_cost_usd: 22000,
    cloud_available: "yes",
    migration_complexity: "medium",
    migration_path: "migrate",
    migration_notes: "SLA configuration needs re-implementation in JSM Cloud",
    phase: 4,
    is_critical: 0,
    agentic_opportunity: "Proactive SLA breach prediction agent with automated escalation",
    ord: 65,
  },
];

export function seedDatabase(db) {
  const themeCount = db.prepare("SELECT COUNT(*) as c FROM themes").get();
  if (themeCount.c > 0) return;

  // Seed themes, sub-dimensions and questions
  for (const theme of THEMES) {
    const themeResult = db.prepare(
      "INSERT INTO themes (name, description, weight) VALUES (?, ?, ?)"
    ).run(theme.name, theme.description, theme.weight);

    const themeId = themeResult.lastInsertRowid;
    const sds = SUB_DIMENSIONS[theme.name] || [];

    for (const sd of sds) {
      const sdResult = db.prepare(
        "INSERT INTO sub_dimensions (theme_id, name, description, weight) VALUES (?, ?, ?, ?)"
      ).run(themeId, sd.name, sd.description, 0.25);

      const sdId = sdResult.lastInsertRowid;

      for (let i = 0; i < QUESTION_TEMPLATES.length; i++) {
        const text = QUESTION_TEMPLATES[i].replace("{sub_dim}", sd.name);
        db.prepare(
          "INSERT INTO questions (sub_dimension_id, text, ord) VALUES (?, ?, ?)"
        ).run(sdId, text, i + 1);
      }
    }
  }

  // Seed applications
  const appCount = db.prepare("SELECT COUNT(*) as c FROM applications").get();
  if (appCount.c === 0) {
    const insertApp = db.prepare(`
      INSERT INTO applications
        (name, product, vendor, user_tier, annual_cost_usd, cloud_available, cloud_product_name,
         migration_complexity, migration_path, migration_notes, phase, is_critical, agentic_opportunity, ord)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `);

    for (const app of APPLICATIONS) {
      insertApp.run(
        app.name,
        app.product,
        app.vendor,
        app.user_tier,
        app.annual_cost_usd,
        app.cloud_available,
        app.cloud_product_name || null,
        app.migration_complexity,
        app.migration_path,
        app.migration_notes || null,
        app.phase,
        app.is_critical,
        app.agentic_opportunity || null,
        app.ord,
      );
    }
  }
}
